data = [
  {
    name: "Nike Slim Shirt",
    category: "fashion",
    image: "/images/p1.jpg",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 4,
    numReviews: 10,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Adidas Fit Shirt",
    category: "fashion",
    image: "/images/p2.jpg",
    price: 100,
    countInStock: 20,
    brand: "Adidas",
    rating: 4,
    numReviews: 10,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Lacoste Free Shirt",
    category: "fashion",
    image: "/images/p3.jpg",
    price: 220,
    countInStock: 0,
    brand: "Lacoste",
    rating: 4,
    numReviews: 17,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Nike Slim Pant",
    category: "fashion",
    image: "/images/p4.jpg",
    price: 78,
    countInStock: 15,
    brand: "Nike",
    rating: 4,
    numReviews: 14,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Puma Slim Pant",
    category: "fashion",
    image: "/images/p5.jpg",
    price: 65,
    countInStock: 5,
    brand: "Puma",
    rating: 4,
    numReviews: 10,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Adidas Fit Pant",
    category: "fashion",
    image: "/images/p6.jpg",
    price: 139,
    countInStock: 12,
    brand: "Adidas",
    rating: 4,
    numReviews: 15,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Nike Slim Shoes",
    category: "fashion",
    image: "/images/shoe1.jpg",
    price: 115,
    countInStock: 8,
    brand: "Nike",
    rating: 4,
    numReviews: 15,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Addidas Shoes",
    category: "fashion",
    image: "/images/shoe2.jpg",
    price: 85,
    countInStock: 15,
    brand: "Nike",
    rating: 4,
    numReviews: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Nike Slim Sneakers",
    category: "fashion",
    image: "/images/shoe3.jpg",
    price: 150,
    countInStock: 20,
    brand: "Nike",
    rating: 3,
    numReviews: 25,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Addidas Sneakers",
    category: "fashion",
    image: "/images/shoe4.jpg",
    price: 120,
    countInStock: 11,
    brand: "Nike",
    rating: 4,
    numReviews: 32,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Nike Sneakers",
    category: "fashion",
    image: "/images/shoe5.jpg",
    price: 132,
    countInStock: 18,
    brand: "Nike",
    rating: 4.2,
    numReviews: 11,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "HP Pavilion 14 laptop",
    category: "electronics",
    image: "/images/laptop3.jpg",
    price: 1510,
    countInStock: 25,
    brand: "HP",
    rating: 4,
    numReviews: 55,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Asus Zenbook 3",
    category: "electronics",
    image: "/images/laptop4.jpg",
    price: 2000,
    countInStock: 8,
    brand: "Asus",
    rating: 4,
    numReviews: 105,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Dell inspiron 14",
    category: "electronics",
    image: "/images/laptop1.jpg",
    price: 1800,
    countInStock: 12,
    brand: "Dell",
    rating: 4,
    numReviews: 105,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Asus vivobook 15",
    category: "electronics",
    image: "/images/laptop2.jpg",
    price: 2500,
    countInStock: 4,
    brand: "Asus",
    rating: 4,
    numReviews: 35,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Low Budget Desktop Pc",
    category: "electronics",
    image: "/images/pc1.jpg",
    price: 800,
    countInStock: 13,
    brand: "Asus",
    rating: 2,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "High Budget Desktop Pc",
    category: "electronics",
    image: "/images/pc2.jpg",
    price: 2800,
    countInStock: 3,
    brand: "Asus",
    rating: 4,
    numReviews: 21,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Gaming Desktop Pc",
    category: "electronics",
    image: "/images/pc4.jpg",
    price: 5000,
    countInStock: 17,
    brand: "Asus",
    rating: 4,
    numReviews: 102,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Coding Computer",
    category: "electronics",
    image: "/images/pc3.jpg",
    price: 1500,
    countInStock: 27,
    brand: "Asus",
    rating: 3,
    numReviews: 2,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Wooden Table 1",
    category: "furniture",
    image: "/images/table.jpg",
    price: 1200,
    countInStock: 7,
    brand: "furniture",
    rating: 3,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Wooden Table 2",
    category: "furniture",
    image: "/images/table2.jpg",
    price: 400,
    countInStock: 6,
    brand: "furniture",
    rating: 4,
    numReviews: 22,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Wooden Table 3",
    category: "furniture",
    image: "/images/table3.jpg",
    price: 650,
    countInStock: 19,
    brand: "furniture",
    rating: 4,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Classic Sofa 1",
    category: "furniture",
    image: "/images/sofa.jpg",
    price: 1340,
    countInStock: 9,
    brand: "furniture",
    rating: 4,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Classic Sofa 2",
    category: "furniture",
    image: "/images/sofa2.jpg",
    price: 1450,
    countInStock: 29,
    brand: "furniture",
    rating: 4,
    numReviews: 32,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },

  {
    name: "Modern Smart Television",
    category: "electronics",
    image: "/images/tv1.jpg",
    price: 840,
    countInStock: 21,
    brand: "Crown",
    rating: 4,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Modern Smart Television 2",
    category: "electronics",
    image: "/images/tv2.jpg",
    price: 700,
    countInStock: 11,
    brand: "Crown",
    rating: 4,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Modern Smart Television 3",
    category: "electronics",
    image: "/images/tv3.jpg",
    price: 1050,
    countInStock: 16,
    brand: "Crown",
    rating: 3,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Latest Watch 1",
    category: "electronics",
    image: "/images/watch1.jpg",
    price: 350,
    countInStock: 5,
    brand: "Crown",
    rating: 3,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Latest Watch 2",
    category: "electronics",
    image: "/images/watch1.jpg",
    price: 300,
    countInStock: 8,
    brand: "Crown",
    rating: 4,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Latest Watch 3",
    category: "electronics",
    image: "/images/watch3.jpg",
    price: 550,
    countInStock: 15,
    brand: "Crown",
    rating: 2,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "The Body",
    category: "books",
    image: "/images/the-body.jpeg",
    price: 250,
    countInStock: 15,
    brand: "Crown",
    rating: 3,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "The Great Gatsby",
    category: "books",
    image: "/images/the-great-gatsby.jpeg",
    price: 400,
    countInStock: 5,
    brand: "Crown",
    rating: 3,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Start With Why",
    category: "books",
    image: "/images/start-with-why.jpeg",
    price: 200,
    countInStock: 12,
    brand: "Crown",
    rating: 3,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Zero To One",
    category: "books",
    image: "/images/zero-to-one.jpeg",
    price: 500,
    countInStock: 9,
    brand: "Crown",
    rating: 4,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Paradise",
    category: "books",
    image: "/images/paradise.jpeg",
    price: 250,
    countInStock: 15,
    brand: "Crown",
    rating: 4,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Origin Of Species",
    category: "books",
    image: "/images/origin-of-species.jpeg",
    price: 450,
    countInStock: 13,
    brand: "Crown",
    rating: 3,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Hell House",
    category: "books",
    image: "/images/hell-house.jpeg",
    price: 150,
    countInStock: 14,
    brand: "Crown",
    rating: 3,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
  {
    name: "Gone Girl",
    category: "books",
    image: "/images/gone-girl.jpeg",
    price: 400,
    countInStock: 18,
    brand: "Crown",
    rating: 4,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis deserunt voluptate iure, quia et omnis delectus architecto repellat ex, maxime ipsa dolorem accusamus odio veritatis.",
  },
];
module.exports = data;
